import Header from "@/components/layout/Header"
import Footer from "@/components/layout/Footer"
import { ThemeProvider } from "./context/ThemeContext"
import "./globals.css"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider >
          <Header />
            <main>{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  )
}
